# nombre de la app
spring.application.name=viajes-farsheen-api
server.port=8080

# conexion a la base de datos de xampp mariadb en el puerto 3307
spring.datasource.url=jdbc:mysql://localhost:3307/viajes-farsheen?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Bogota
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# por si acaso para pruebas locales con h2 si xampp esta apagado (delfinDb):
# spring.datasource.url=jdbc:h2:mem:viajesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# jpa hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# la documentacion del swagger ui
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method